# UniCeption encoder string used for selecting encoder class (python3 -m uniception.models.encoders.list)
encoder_str: "pixio"
# Name of the encoder
name: "pixio"
# Data normalization type
data_norm_type: "pixio"
# Flag to indicate whether to use gradient checkpointing for encoder
gradient_checkpointing: True
# Flag to indicate whether model class uses torch hub
uses_torch_hub: False
